sources:
  # RSS Sources - Handled by RSS Template
  - name: babypips
    type: rss
    url: https://www.babypips.com/feed.rss
    rate_limit: 1
    max_articles: 50
    content_type: forex
    
  - name: fxstreet
    type: rss
    url: https://www.fxstreet.com/rss/news
    rate_limit: 1
    max_articles: 50
    content_type: forex
    
  - name: forexlive
    type: rss
    url: https://www.forexlive.com/feed/
    rate_limit: 1
    max_articles: 50
    content_type: forex
    
  - name: bloomberg_forex
    type: rss
    url: https://feeds.bloomberg.com/markets/news.rss
    rate_limit: 2
    max_articles: 40
    content_type: forex

  # HTML Sources - For future HTML template implementation
  # Currently using fallback behavior until HTML template is created
  - name: kabutan
    type: html_scraping
    url: https://kabutan.jp/news/marketnews/
    selectors:
      title: "h1, .title, .headline"
      content: ".article-body, .content, .post-content"
      author: ".author, .by-author"
    translate: true
    rate_limit: 2
    max_articles: 30
    content_type: stocks
    
  - name: poundsterlinglive
    type: html_scraping
    url: https://www.poundsterlinglive.com/markets
    selectors:
      title: "h1, .title, .headline"
      content: ".content, .article-content, .post-content"
      author: ".author, .by-author"
    rate_limit: 2
    max_articles: 30
    content_type: forex