sources:
  # RSS Sources - Handled by RSS Template
  - name: babypips
    type: rss
    url: https://www.babypips.com/feed.rss
    rate_limit: 1
    max_articles: 50
    content_type: forex
    
  - name: fxstreet
    type: rss
    url: https://www.fxstreet.com/rss/news
    rate_limit: 1
    max_articles: 50
    content_type: forex
    
  # FIXED: ForexLive with enhanced error handling
  - name: forexlive
    type: rss
    url: https://www.forexlive.com/feed/
    rate_limit: 3  # Increased for stability
    max_articles: 50
    content_type: forex
    
  # FIXED: PoundSterlingLive with potential RSS endpoints
  - name: poundsterlinglive
    type: rss
    url: https://www.poundsterlinglive.com/feed
    rate_limit: 2
    max_articles: 30
    content_type: forex

  # RESTORED: Kabutan as HTML scraping (properly configured)
  - name: kabutan
    type: html_scraping
    url: https://kabutan.jp/news/marketnews/
    selectors:
      title: ".news-title, .ttl, h2, h3"
      content: ".news-content, .article-body, .lead"  
      link: "a[href*='/news/']"
      date: ".date, .time, .published"
    translate: true
    rate_limit: 3
    max_articles: 20
    content_type: stocks

  # Optional: Add working alternatives
  - name: bloomberg_forex
    type: rss
    url: https://feeds.bloomberg.com/markets/news.rss
    rate_limit: 2
    max_articles: 40
    content_type: forex
  